## Missing Data

In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.DataFrame({'A': [1, 2, np.nan, 4],
                   'B': [5, np.nan, np.nan, 8],
                   'C': [10, 20, 30, 40]})

In [4]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

## Drop Values

In [5]:
df.dropna()

     A    B   C
0  1.0  5.0  10
3  4.0  8.0  40

In [6]:
df.dropna(axis = 1)

    C
0  10
1  20
2  30
3  40

In [8]:
df.dropna(axis = 1, thresh = 3)

     A   C
0  1.0  10
1  2.0  20
2  NaN  30
3  4.0  40

## Fill in Values

In [9]:
df.fillna(value = 'FILL VALUE')

            A           B   C
0           1           5  10
1           2  FILL VALUE  20
2  FILL VALUE  FILL VALUE  30
3           4           8  40

In [10]:
df.fillna(value = 0)

     A    B   C
0  1.0  5.0  10
1  2.0  0.0  20
2  0.0  0.0  30
3  4.0  8.0  40

In [12]:
df['A'] = df['A'].fillna(0)

In [13]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  0.0  NaN  30
3  4.0  8.0  40

In [14]:
df['B'] = df.fillna(df['B'].mean())

In [17]:
df = pd.DataFrame({'A': [1, 2, np.nan, 4],
                   'B': [5, np.nan, np.nan, 8],
                   'C': [10, 20, 30, 40]})
df.fillna(df.mean())

          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  20
2  2.333333  6.5  30
3  4.000000  8.0  40